steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ema-hikma-health-admin-app:$COMMIT_SHA',
          '--build-arg', 'app_env_arg=prod',
          '--build-arg', 'instance_url_arg=${_INSTANCE_URL}',
          '.' ]

- name: 'gcr.io/cloud-builders/kubectl'
  env: ['CLOUDSDK_COMPUTE_ZONE=europe-central2-a', 'CLOUDSDK_CONTAINER_CLUSTER=ema-prod']
  args: ['set', 'image', 'deployment/ema-hikma-health-admin-app',
       'ema-hikma-health-admin-app=gcr.io/$PROJECT_ID/ema-hikma-health-admin-app:$COMMIT_SHA']


images:
- 'gcr.io/$PROJECT_ID/ema-hikma-health-admin-app:$COMMIT_SHA'
